apiVersion: v2
name: ffc-demo-payment-service-infra
description: A ASO Helm chart to deploy the FFC Demo Payment Service Infrastructure
version: 0.0.1
dependencies:
- name: adp-aso-helm-library
  version: ^0.0.1
  repository: oci://ssvadpinfcr3401.azurecr.io/helm

